# Generated by Django 5.2.4 on 2025-07-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0005_documenttype_educationlevel_employee_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
