# Generated by Django 5.2.4 on 2025-07-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0007_alter_employee_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationqualification',
            options={'ordering': ['-graduation_date'], 'verbose_name': 'Education Qualification', 'verbose_name_plural': 'Education Qualifications'},
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='board_university',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='grade_point',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='institution_city',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='institution_country',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='institution_state',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='major_subject',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='minor_subject',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='result',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='verification_date',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='verified_by',
        ),
    ]
