# Generated by Django 5.2.4 on 2025-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0010_jobexperience_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='expiry_applicable',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='is_confidential',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='issuing_authority',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
