# Generated by Django 5.2.4 on 2025-07-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0006_remove_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='currency',
            field=models.CharField(default='BDT', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
    ]
