# Generated by Django 5.2.4 on 2025-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0009_remove_jobexperience_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('CONSULTANT', 'Consultant')], max_length=20, null=True, verbose_name='Employment Type'),
        ),
    ]
