# Generated by Django 5.2.4 on 2025-07-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0011_remove_documenttype_expiry_applicable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='currency',
        ),
    ]
