# Generated by Django 5.2.4 on 2025-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0012_remove_employee_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_dependent',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_emergency_contact',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_nominee',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='photo',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('SPOUSE', 'Spouse'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('OTHER', 'Other')], max_length=20, verbose_name='Relationship'),
        ),
    ]
