# Generated by Django 5.2.4 on 2025-07-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0013_remove_familymember_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permanent_city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permanent_country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permanent_postal_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permanent_state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='present_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='present_city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='present_country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='present_postal_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='present_state',
        ),
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.CharField(blank=True, default='BDT', max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Permanent District'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_division',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Permanent Division'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_police_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Permanent Police Station (PS)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_post_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Permanent Post Office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_postal_code_bd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Permanent Postal Code'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_road_block',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Permanent Road/Block/Sector'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_village_house',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Permanent Village/House No.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Present District'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_division',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Present Division'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_police_station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Present Police Station (PS)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_post_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Present Post Office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_postal_code_bd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Present Postal Code'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_road_block',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Present Road/Block/Sector'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_village_house',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Present Village/House No.'),
        ),
    ]
