# Generated by Django 4.2.20 on 2025-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0014_remove_employee_permanent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divo rced'), ('W', 'Widowed'), ('SE', 'Separated')], max_length=2, verbose_name='Marital Status'),
        ),
    ]
